language: php

php:
    - '7.0'
    - '7.1'

install:
    - travis_retry composer install --no-interaction

before_script:
    - cp .env.testing .env
    - composer install
    - php artisan key:generat

script: vendor/bin/phpunit --configuration phpunit.xml